force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Propery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/Available_Units__c.field-meta.xml
<CustomField>
    <fullName>Available_Units__c</fullName>
    <label>Available Units</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Total_Units__c.field-meta.xml
<CustomField>
    <fullName>Total_Units__c</fullName>
    <label>Total Units</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BookingAutoCancelBatchTest.cls
@isTest
public class BookingAutoCancelBatchTest {

    @isTest
    static void testBatchExecution(){

        Property__c property = new Property__c(
            Name = 'Test Property',
            Total_Units__c = 10,
            Available_Units__c = 5
        );

        insert property;

        Booking__c booking = new Booking__c(
    Status__c = 'Pending',
    Booking_Date__c = System.today().addDays(-10),
    Property__c = property.Id
);

        insert booking;

        Test.startTest();

        BookingAutoCancelBatch batch = new BookingAutoCancelBatch();

        Database.executeBatch(batch);

        Test.stopTest();

        Booking__c updatedBooking = [
            SELECT Status__c
            FROM Booking__c
            WHERE Id = :booking.Id
        ];

        System.assertEquals('Cancelled', updatedBooking.Status__c);

    }

}