force-app/main/default/objects/Invoice__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <label>Propery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BookingTriggerHandler.cls
public class BookingTriggerHandler {

    public static void createInvoices(List<Booking__c> newBookings, Map<Id, Booking__c> oldMap) {

        List<Invoice__c> invoicesToInsert = new List<Invoice__c>();
        Set<Id> propertyIds = new Set<Id>();

        for (Booking__c b : newBookings) {
            if (b.Property__c != null) {
                propertyIds.add(b.Property__c);
            }
        }

        Map<Id, Property__c> propertyMap = new Map<Id, Property__c>(
            [SELECT Id, Price_Per_Unit__c FROM Property__c WHERE Id IN :propertyIds]
        );

        for (Booking__c b : newBookings) {

            Boolean shouldCreateInvoice = false;

            if (oldMap == null) {
                if (b.Status__c == 'Confirmed') {
                    shouldCreateInvoice = true;
                }
            } 
            else {
                if (b.Status__c == 'Confirmed' &&
                    oldMap.get(b.Id).Status__c != 'Confirmed') {
                    shouldCreateInvoice = true;
                }
            }

            if (shouldCreateInvoice && propertyMap.containsKey(b.Property__c)) {

                Property__c prop = propertyMap.get(b.Property__c);

               Invoice__c inv = new Invoice__c();
inv.Name = 'INV-' + b.Id;
inv.Booking__c = b.Id;
inv.Invoice_Amount__c = prop.Price_Per_Unit__c;
inv.Due_Date__c = b.Booking_Date__c.addDays(7);
inv.Status__c = 'Pending';

                invoicesToInsert.add(inv);
            }
        }

        if (!invoicesToInsert.isEmpty()) {
            insert invoicesToInsert;
        }
    }
}